name: python-cicd

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: build project
    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python Environment 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run code linter with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: run tests with PyTest
        run: pytest

      - name: login to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/python-cicd

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/python-cicd
